"LR": 0.0065
"NUM_ENVS": 1024 
"NUM_STEPS": 128 
"TOTAL_TIMESTEPS": 1e9
"FC_DIM_SIZE": 128
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 4
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.1
"SCALE_CLIP_EPS": False
"ENT_COEF": 0.01
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ACTIVATION": "relu"
"ENV_NAME": "hanabi"
"SEED": 30
"NUM_SEEDS": 1

"ANNEAL_LR": True

# WandB Params
"WANDB_MODE": "online"
"ENTITY": "your-entity"
"PROJECT": "your-project"



"ENV_KWARGS": {
  "num_agents": 2,
  "train_pre_policy": True,
  "intrinsic_reward_ratio": 0.035,
  "if_augment_obs": True,
  "convention_type": "save_5",
  "intervene_two_agents": False,
}




"NUM_PROXY_AGENTS": 1
"OBS_ENC_HIDDEN_DIM": 128
"TEMPERATURE": 1.0
"NODE_FEATURE_DIM": 8


"PRE_POLICY_HIDDEN_DIM": 128
"PRE_POLICY_OUTPUT_DIM": 256
"SHARE_CRITIC": False


"RUN_BASELINE": False

"PRE_POLICY_EMD_INPUT_ACTOR": False

"CONFIG_NAME": MAPPO_PRE_POLICY